# Generated by Django 2.2.4 on 2019-08-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='word_length',
            field=models.IntegerField(default=0),
        ),
    ]
